### ISSUE TITLE
Double arrows opening tag properties XML

### ISSUE THREAD

**Issue by IIsaku** [cdcharlebois/vscode-mx-pluggable-widget-utilities#2]
![Schermopname 2020-08-24 om 09 33 55](https://user-images.githubusercontent.com/16718722/91017954-3194c800-e5ef-11ea-908a-342faef1b2f9.gif)

**Comment by cdcharlebois** [comment]
Hi @IIsaku, try without typing the opening angle-bracket. The snippet puts it in for you. Just start typing `pprop`
